//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.02.13 at 01:05:32 PM CET 
//


package pl.gov.crd.xml.schematy.dziedzinowe.mf._2022._01._05.ed.definicjetypy;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the pl.gov.crd.xml.schematy.dziedzinowe.mf._2022._01._05.ed.definicjetypy package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: pl.gov.crd.xml.schematy.dziedzinowe.mf._2022._01._05.ed.definicjetypy
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TOsobaNiefizycznaPelna1 }
     * 
     */
    public TOsobaNiefizycznaPelna1 createTOsobaNiefizycznaPelna1() {
        return new TOsobaNiefizycznaPelna1();
    }

    /**
     * Create an instance of {@link TPodmiotDowolnyPelny1 }
     * 
     */
    public TPodmiotDowolnyPelny1 createTPodmiotDowolnyPelny1() {
        return new TPodmiotDowolnyPelny1();
    }

    /**
     * Create an instance of {@link TPodmiotDowolnyPelny }
     * 
     */
    public TPodmiotDowolnyPelny createTPodmiotDowolnyPelny() {
        return new TPodmiotDowolnyPelny();
    }

    /**
     * Create an instance of {@link TOsobaNiefizycznaPelna }
     * 
     */
    public TOsobaNiefizycznaPelna createTOsobaNiefizycznaPelna() {
        return new TOsobaNiefizycznaPelna();
    }

    /**
     * Create an instance of {@link TPodmiotDowolny2 }
     * 
     */
    public TPodmiotDowolny2 createTPodmiotDowolny2() {
        return new TPodmiotDowolny2();
    }

    /**
     * Create an instance of {@link TPodmiotDowolny1 }
     * 
     */
    public TPodmiotDowolny1 createTPodmiotDowolny1() {
        return new TPodmiotDowolny1();
    }

    /**
     * Create an instance of {@link TOsobaFizycznaPelna1 }
     * 
     */
    public TOsobaFizycznaPelna1 createTOsobaFizycznaPelna1() {
        return new TOsobaFizycznaPelna1();
    }

    /**
     * Create an instance of {@link TOsobaFizycznaPelna }
     * 
     */
    public TOsobaFizycznaPelna createTOsobaFizycznaPelna() {
        return new TOsobaFizycznaPelna();
    }

    /**
     * Create an instance of {@link TPodmiotDowolny }
     * 
     */
    public TPodmiotDowolny createTPodmiotDowolny() {
        return new TPodmiotDowolny();
    }

    /**
     * Create an instance of {@link TOsobaFizyczna4 }
     * 
     */
    public TOsobaFizyczna4 createTOsobaFizyczna4() {
        return new TOsobaFizyczna4();
    }

    /**
     * Create an instance of {@link TOsobaNiefizyczna2 }
     * 
     */
    public TOsobaNiefizyczna2 createTOsobaNiefizyczna2() {
        return new TOsobaNiefizyczna2();
    }

    /**
     * Create an instance of {@link TOsobaNiefizyczna1 }
     * 
     */
    public TOsobaNiefizyczna1 createTOsobaNiefizyczna1() {
        return new TOsobaNiefizyczna1();
    }

    /**
     * Create an instance of {@link TOsobaNiefizyczna }
     * 
     */
    public TOsobaNiefizyczna createTOsobaNiefizyczna() {
        return new TOsobaNiefizyczna();
    }

    /**
     * Create an instance of {@link TOsobaFizyczna2 }
     * 
     */
    public TOsobaFizyczna2 createTOsobaFizyczna2() {
        return new TOsobaFizyczna2();
    }

    /**
     * Create an instance of {@link TOsobaFizyczna3 }
     * 
     */
    public TOsobaFizyczna3 createTOsobaFizyczna3() {
        return new TOsobaFizyczna3();
    }

    /**
     * Create an instance of {@link TOsobaFizyczna5 }
     * 
     */
    public TOsobaFizyczna5 createTOsobaFizyczna5() {
        return new TOsobaFizyczna5();
    }

    /**
     * Create an instance of {@link TOsobaFizyczna1 }
     * 
     */
    public TOsobaFizyczna1 createTOsobaFizyczna1() {
        return new TOsobaFizyczna1();
    }

    /**
     * Create an instance of {@link TOsobaFizyczna }
     * 
     */
    public TOsobaFizyczna createTOsobaFizyczna() {
        return new TOsobaFizyczna();
    }

    /**
     * Create an instance of {@link TAdres }
     * 
     */
    public TAdres createTAdres() {
        return new TAdres();
    }

    /**
     * Create an instance of {@link TAdres1 }
     * 
     */
    public TAdres1 createTAdres1() {
        return new TAdres1();
    }

    /**
     * Create an instance of {@link TAdresPolski }
     * 
     */
    public TAdresPolski createTAdresPolski() {
        return new TAdresPolski();
    }

    /**
     * Create an instance of {@link TAdresPolski1 }
     * 
     */
    public TAdresPolski1 createTAdresPolski1() {
        return new TAdresPolski1();
    }

    /**
     * Create an instance of {@link TAdresZagraniczny }
     * 
     */
    public TAdresZagraniczny createTAdresZagraniczny() {
        return new TAdresZagraniczny();
    }

    /**
     * Create an instance of {@link TIdentyfikatorOsobyFizycznej }
     * 
     */
    public TIdentyfikatorOsobyFizycznej createTIdentyfikatorOsobyFizycznej() {
        return new TIdentyfikatorOsobyFizycznej();
    }

    /**
     * Create an instance of {@link TIdentyfikatorOsobyFizycznej1 }
     * 
     */
    public TIdentyfikatorOsobyFizycznej1 createTIdentyfikatorOsobyFizycznej1() {
        return new TIdentyfikatorOsobyFizycznej1();
    }

    /**
     * Create an instance of {@link TIdentyfikatorOsobyFizycznej2 }
     * 
     */
    public TIdentyfikatorOsobyFizycznej2 createTIdentyfikatorOsobyFizycznej2() {
        return new TIdentyfikatorOsobyFizycznej2();
    }

    /**
     * Create an instance of {@link TIdentyfikatorOsobyFizycznejPelny }
     * 
     */
    public TIdentyfikatorOsobyFizycznejPelny createTIdentyfikatorOsobyFizycznejPelny() {
        return new TIdentyfikatorOsobyFizycznejPelny();
    }

    /**
     * Create an instance of {@link TIdentyfikatorOsobyFizycznejZagranicznej }
     * 
     */
    public TIdentyfikatorOsobyFizycznejZagranicznej createTIdentyfikatorOsobyFizycznejZagranicznej() {
        return new TIdentyfikatorOsobyFizycznejZagranicznej();
    }

    /**
     * Create an instance of {@link TIdentyfikatorOsobyNiefizycznej }
     * 
     */
    public TIdentyfikatorOsobyNiefizycznej createTIdentyfikatorOsobyNiefizycznej() {
        return new TIdentyfikatorOsobyNiefizycznej();
    }

    /**
     * Create an instance of {@link TIdentyfikatorOsobyNiefizycznej1 }
     * 
     */
    public TIdentyfikatorOsobyNiefizycznej1 createTIdentyfikatorOsobyNiefizycznej1() {
        return new TIdentyfikatorOsobyNiefizycznej1();
    }

    /**
     * Create an instance of {@link TIdentyfikatorOsobyNiefizycznejPelny }
     * 
     */
    public TIdentyfikatorOsobyNiefizycznejPelny createTIdentyfikatorOsobyNiefizycznejPelny() {
        return new TIdentyfikatorOsobyNiefizycznejPelny();
    }

    /**
     * Create an instance of {@link TIdentyfikatorOsobyNiefizycznejZagranicznej }
     * 
     */
    public TIdentyfikatorOsobyNiefizycznejZagranicznej createTIdentyfikatorOsobyNiefizycznejZagranicznej() {
        return new TIdentyfikatorOsobyNiefizycznejZagranicznej();
    }

    /**
     * Create an instance of {@link TPodmiotDowolnyBezAdresu }
     * 
     */
    public TPodmiotDowolnyBezAdresu createTPodmiotDowolnyBezAdresu() {
        return new TPodmiotDowolnyBezAdresu();
    }

    /**
     * Create an instance of {@link TPodmiotDowolnyBezAdresu1 }
     * 
     */
    public TPodmiotDowolnyBezAdresu1 createTPodmiotDowolnyBezAdresu1() {
        return new TPodmiotDowolnyBezAdresu1();
    }

    /**
     * Create an instance of {@link TPodmiotDowolnyBezAdresu2 }
     * 
     */
    public TPodmiotDowolnyBezAdresu2 createTPodmiotDowolnyBezAdresu2() {
        return new TPodmiotDowolnyBezAdresu2();
    }

    /**
     * Create an instance of {@link TPodmiotDowolnyBezAdresu3 }
     * 
     */
    public TPodmiotDowolnyBezAdresu3 createTPodmiotDowolnyBezAdresu3() {
        return new TPodmiotDowolnyBezAdresu3();
    }

    /**
     * Create an instance of {@link TOsobaNiefizycznaPelna1 .AdresSiedziby }
     * 
     */
    public TOsobaNiefizycznaPelna1 .AdresSiedziby createTOsobaNiefizycznaPelna1AdresSiedziby() {
        return new TOsobaNiefizycznaPelna1 .AdresSiedziby();
    }

    /**
     * Create an instance of {@link TPodmiotDowolnyPelny1 .AdresZamieszkaniaSiedziby }
     * 
     */
    public TPodmiotDowolnyPelny1 .AdresZamieszkaniaSiedziby createTPodmiotDowolnyPelny1AdresZamieszkaniaSiedziby() {
        return new TPodmiotDowolnyPelny1 .AdresZamieszkaniaSiedziby();
    }

    /**
     * Create an instance of {@link TPodmiotDowolnyPelny.AdresZamieszkaniaSiedziby }
     * 
     */
    public TPodmiotDowolnyPelny.AdresZamieszkaniaSiedziby createTPodmiotDowolnyPelnyAdresZamieszkaniaSiedziby() {
        return new TPodmiotDowolnyPelny.AdresZamieszkaniaSiedziby();
    }

    /**
     * Create an instance of {@link TOsobaNiefizycznaPelna.AdresSiedziby }
     * 
     */
    public TOsobaNiefizycznaPelna.AdresSiedziby createTOsobaNiefizycznaPelnaAdresSiedziby() {
        return new TOsobaNiefizycznaPelna.AdresSiedziby();
    }

    /**
     * Create an instance of {@link TPodmiotDowolny2 .AdresZamieszkaniaSiedziby }
     * 
     */
    public TPodmiotDowolny2 .AdresZamieszkaniaSiedziby createTPodmiotDowolny2AdresZamieszkaniaSiedziby() {
        return new TPodmiotDowolny2 .AdresZamieszkaniaSiedziby();
    }

    /**
     * Create an instance of {@link TPodmiotDowolny1 .AdresZamieszkaniaSiedziby }
     * 
     */
    public TPodmiotDowolny1 .AdresZamieszkaniaSiedziby createTPodmiotDowolny1AdresZamieszkaniaSiedziby() {
        return new TPodmiotDowolny1 .AdresZamieszkaniaSiedziby();
    }

    /**
     * Create an instance of {@link TOsobaFizycznaPelna1 .AdresZamieszkania }
     * 
     */
    public TOsobaFizycznaPelna1 .AdresZamieszkania createTOsobaFizycznaPelna1AdresZamieszkania() {
        return new TOsobaFizycznaPelna1 .AdresZamieszkania();
    }

    /**
     * Create an instance of {@link TOsobaFizycznaPelna.AdresZamieszkania }
     * 
     */
    public TOsobaFizycznaPelna.AdresZamieszkania createTOsobaFizycznaPelnaAdresZamieszkania() {
        return new TOsobaFizycznaPelna.AdresZamieszkania();
    }

    /**
     * Create an instance of {@link TPodmiotDowolny.AdresZamieszkaniaSiedziby }
     * 
     */
    public TPodmiotDowolny.AdresZamieszkaniaSiedziby createTPodmiotDowolnyAdresZamieszkaniaSiedziby() {
        return new TPodmiotDowolny.AdresZamieszkaniaSiedziby();
    }

    /**
     * Create an instance of {@link TOsobaFizyczna4 .AdresZamieszkania }
     * 
     */
    public TOsobaFizyczna4 .AdresZamieszkania createTOsobaFizyczna4AdresZamieszkania() {
        return new TOsobaFizyczna4 .AdresZamieszkania();
    }

    /**
     * Create an instance of {@link TOsobaNiefizyczna2 .AdresSiedziby }
     * 
     */
    public TOsobaNiefizyczna2 .AdresSiedziby createTOsobaNiefizyczna2AdresSiedziby() {
        return new TOsobaNiefizyczna2 .AdresSiedziby();
    }

    /**
     * Create an instance of {@link TOsobaNiefizyczna1 .AdresSiedziby }
     * 
     */
    public TOsobaNiefizyczna1 .AdresSiedziby createTOsobaNiefizyczna1AdresSiedziby() {
        return new TOsobaNiefizyczna1 .AdresSiedziby();
    }

    /**
     * Create an instance of {@link TOsobaNiefizyczna.AdresSiedziby }
     * 
     */
    public TOsobaNiefizyczna.AdresSiedziby createTOsobaNiefizycznaAdresSiedziby() {
        return new TOsobaNiefizyczna.AdresSiedziby();
    }

    /**
     * Create an instance of {@link TOsobaFizyczna2 .AdresZamieszkania }
     * 
     */
    public TOsobaFizyczna2 .AdresZamieszkania createTOsobaFizyczna2AdresZamieszkania() {
        return new TOsobaFizyczna2 .AdresZamieszkania();
    }

    /**
     * Create an instance of {@link TOsobaFizyczna3 .AdresZamieszkania }
     * 
     */
    public TOsobaFizyczna3 .AdresZamieszkania createTOsobaFizyczna3AdresZamieszkania() {
        return new TOsobaFizyczna3 .AdresZamieszkania();
    }

    /**
     * Create an instance of {@link TOsobaFizyczna5 .AdresZamieszkania }
     * 
     */
    public TOsobaFizyczna5 .AdresZamieszkania createTOsobaFizyczna5AdresZamieszkania() {
        return new TOsobaFizyczna5 .AdresZamieszkania();
    }

    /**
     * Create an instance of {@link TOsobaFizyczna1 .AdresZamieszkania }
     * 
     */
    public TOsobaFizyczna1 .AdresZamieszkania createTOsobaFizyczna1AdresZamieszkania() {
        return new TOsobaFizyczna1 .AdresZamieszkania();
    }

    /**
     * Create an instance of {@link TOsobaFizyczna.AdresZamieszkania }
     * 
     */
    public TOsobaFizyczna.AdresZamieszkania createTOsobaFizycznaAdresZamieszkania() {
        return new TOsobaFizyczna.AdresZamieszkania();
    }

}
