spring.application.name=ksef

sdk.config.base-uri=https://api.ksef.mf.gov.pl
sdk.config.suffix-uri=v2
sdk.config.qr-uri=https://qr.ksef.mf.gov.pl
sdk.config.request-timeout=100
sdk.config.lighthouse-base-uri=https://api-latarnia.ksef.mf.gov.pl/

# nie zapomnij zmienic na produkcje
gg.jte.developmentMode=false
gg.jte.usePrecompiledTemplates=true
