# nie zapomnij zmienic na produkcje
gg.jte.developmentMode=true
gg.jte.usePrecompiledTemplates=false


#sdk.config.base-uri=https://api-test.ksef.mf.gov.pl/
#sdk.config.suffix-uri=v2


#sdk.config.qr-uri=https://qr.ksef.mf.gov.pl
#sdk.config.request-timeout=100
#sdk.config.lighthouse-base-uri=https://api-latarnia.ksef.mf.gov.pl/

localConfigFileName=settings-local.json

spring.jpa.properties.javax.persistence.schema-generation.create-source=metadata
spring.jpa.properties.javax.persistence.schema-generation.scripts.action=create
spring.jpa.properties.javax.persistence.schema-generation.scripts.create-target=create.sql
spring.jpa.properties.hibernate.hbm2ddl.schema-generation.script.append=false

spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.delimiter=;

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.trace=false
spring.h2.console.settings.web-allow-others=false