# nie zapomnij zmienic na produkcje
gg.jte.developmentMode=true
gg.jte.usePrecompiledTemplates=false


sdk.config.base-uri=https://api-test.ksef.mf.gov.pl/


#sdk.config.qr-uri=https://qr.ksef.mf.gov.pl
#sdk.config.request-timeout=100
#sdk.config.lighthouse-base-uri=https://api-latarnia.ksef.mf.gov.pl/

localConfigFileName=settings-local.json

spring.jpa.properties.javax.persistence.schema-generation.create-source=metadata
spring.jpa.properties.javax.persistence.schema-generation.scripts.action=create
spring.jpa.properties.javax.persistence.schema-generation.scripts.create-target=src/main/resources/db/migration/V1_0__initial_schema.sql
spring.jpa.properties.hibernate.hbm2ddl.schema-generation.script.append=false

spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.delimiter=;