//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.02.13 at 11:47:47 AM CET 
//


package pl.gov.crd.wzor._2025._06._25._13775;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the pl.gov.crd.wzor._2025._06._25._13775 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: pl.gov.crd.wzor._2025._06._25._13775
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Faktura }
     * 
     */
    public Faktura createFaktura() {
        return new Faktura();
    }

    /**
     * Create an instance of {@link Faktura.Zalacznik }
     * 
     */
    public Faktura.Zalacznik createFakturaZalacznik() {
        return new Faktura.Zalacznik();
    }

    /**
     * Create an instance of {@link Faktura.Zalacznik.BlokDanych }
     * 
     */
    public Faktura.Zalacznik.BlokDanych createFakturaZalacznikBlokDanych() {
        return new Faktura.Zalacznik.BlokDanych();
    }

    /**
     * Create an instance of {@link Faktura.Zalacznik.BlokDanych.Tabela }
     * 
     */
    public Faktura.Zalacznik.BlokDanych.Tabela createFakturaZalacznikBlokDanychTabela() {
        return new Faktura.Zalacznik.BlokDanych.Tabela();
    }

    /**
     * Create an instance of {@link Faktura.Zalacznik.BlokDanych.Tabela.TNaglowek }
     * 
     */
    public Faktura.Zalacznik.BlokDanych.Tabela.TNaglowek createFakturaZalacznikBlokDanychTabelaTNaglowek() {
        return new Faktura.Zalacznik.BlokDanych.Tabela.TNaglowek();
    }

    /**
     * Create an instance of {@link Faktura.Zalacznik.BlokDanych.Tabela.TNaglowek.Kol }
     * 
     */
    public Faktura.Zalacznik.BlokDanych.Tabela.TNaglowek.Kol createFakturaZalacznikBlokDanychTabelaTNaglowekKol() {
        return new Faktura.Zalacznik.BlokDanych.Tabela.TNaglowek.Kol();
    }

    /**
     * Create an instance of {@link Faktura.Stopka }
     * 
     */
    public Faktura.Stopka createFakturaStopka() {
        return new Faktura.Stopka();
    }

    /**
     * Create an instance of {@link Faktura.Fa }
     * 
     */
    public Faktura.Fa createFakturaFa() {
        return new Faktura.Fa();
    }

    /**
     * Create an instance of {@link Faktura.Fa.Zamowienie }
     * 
     */
    public Faktura.Fa.Zamowienie createFakturaFaZamowienie() {
        return new Faktura.Fa.Zamowienie();
    }

    /**
     * Create an instance of {@link Faktura.Fa.WarunkiTransakcji }
     * 
     */
    public Faktura.Fa.WarunkiTransakcji createFakturaFaWarunkiTransakcji() {
        return new Faktura.Fa.WarunkiTransakcji();
    }

    /**
     * Create an instance of {@link Faktura.Fa.WarunkiTransakcji.Transport }
     * 
     */
    public Faktura.Fa.WarunkiTransakcji.Transport createFakturaFaWarunkiTransakcjiTransport() {
        return new Faktura.Fa.WarunkiTransakcji.Transport();
    }

    /**
     * Create an instance of {@link Faktura.Fa.Platnosc }
     * 
     */
    public Faktura.Fa.Platnosc createFakturaFaPlatnosc() {
        return new Faktura.Fa.Platnosc();
    }

    /**
     * Create an instance of {@link Faktura.Fa.Platnosc.TerminPlatnosci }
     * 
     */
    public Faktura.Fa.Platnosc.TerminPlatnosci createFakturaFaPlatnoscTerminPlatnosci() {
        return new Faktura.Fa.Platnosc.TerminPlatnosci();
    }

    /**
     * Create an instance of {@link Faktura.Fa.Rozliczenie }
     * 
     */
    public Faktura.Fa.Rozliczenie createFakturaFaRozliczenie() {
        return new Faktura.Fa.Rozliczenie();
    }

    /**
     * Create an instance of {@link Faktura.Fa.Adnotacje }
     * 
     */
    public Faktura.Fa.Adnotacje createFakturaFaAdnotacje() {
        return new Faktura.Fa.Adnotacje();
    }

    /**
     * Create an instance of {@link Faktura.Fa.Adnotacje.NoweSrodkiTransportu }
     * 
     */
    public Faktura.Fa.Adnotacje.NoweSrodkiTransportu createFakturaFaAdnotacjeNoweSrodkiTransportu() {
        return new Faktura.Fa.Adnotacje.NoweSrodkiTransportu();
    }

    /**
     * Create an instance of {@link Faktura.PodmiotUpowazniony }
     * 
     */
    public Faktura.PodmiotUpowazniony createFakturaPodmiotUpowazniony() {
        return new Faktura.PodmiotUpowazniony();
    }

    /**
     * Create an instance of {@link Faktura.Podmiot3 }
     * 
     */
    public Faktura.Podmiot3 createFakturaPodmiot3() {
        return new Faktura.Podmiot3();
    }

    /**
     * Create an instance of {@link Faktura.Podmiot2 }
     * 
     */
    public Faktura.Podmiot2 createFakturaPodmiot2() {
        return new Faktura.Podmiot2();
    }

    /**
     * Create an instance of {@link Faktura.Podmiot1 }
     * 
     */
    public Faktura.Podmiot1 createFakturaPodmiot1() {
        return new Faktura.Podmiot1();
    }

    /**
     * Create an instance of {@link pl.gov.crd.wzor._2025._06._25._13775.TNaglowek }
     * 
     */
    public pl.gov.crd.wzor._2025._06._25._13775.TNaglowek createTNaglowek() {
        return new pl.gov.crd.wzor._2025._06._25._13775.TNaglowek();
    }

    /**
     * Create an instance of {@link TAdres }
     * 
     */
    public TAdres createTAdres() {
        return new TAdres();
    }

    /**
     * Create an instance of {@link TKluczWartosc }
     * 
     */
    public TKluczWartosc createTKluczWartosc() {
        return new TKluczWartosc();
    }

    /**
     * Create an instance of {@link TRachunekBankowy }
     * 
     */
    public TRachunekBankowy createTRachunekBankowy() {
        return new TRachunekBankowy();
    }

    /**
     * Create an instance of {@link TPodmiot1 }
     * 
     */
    public TPodmiot1 createTPodmiot1() {
        return new TPodmiot1();
    }

    /**
     * Create an instance of {@link TPodmiot2 }
     * 
     */
    public TPodmiot2 createTPodmiot2() {
        return new TPodmiot2();
    }

    /**
     * Create an instance of {@link TPodmiot3 }
     * 
     */
    public TPodmiot3 createTPodmiot3() {
        return new TPodmiot3();
    }

    /**
     * Create an instance of {@link Faktura.Zalacznik.BlokDanych.MetaDane }
     * 
     */
    public Faktura.Zalacznik.BlokDanych.MetaDane createFakturaZalacznikBlokDanychMetaDane() {
        return new Faktura.Zalacznik.BlokDanych.MetaDane();
    }

    /**
     * Create an instance of {@link Faktura.Zalacznik.BlokDanych.Tekst }
     * 
     */
    public Faktura.Zalacznik.BlokDanych.Tekst createFakturaZalacznikBlokDanychTekst() {
        return new Faktura.Zalacznik.BlokDanych.Tekst();
    }

    /**
     * Create an instance of {@link Faktura.Zalacznik.BlokDanych.Tabela.TMetaDane }
     * 
     */
    public Faktura.Zalacznik.BlokDanych.Tabela.TMetaDane createFakturaZalacznikBlokDanychTabelaTMetaDane() {
        return new Faktura.Zalacznik.BlokDanych.Tabela.TMetaDane();
    }

    /**
     * Create an instance of {@link Faktura.Zalacznik.BlokDanych.Tabela.Wiersz }
     * 
     */
    public Faktura.Zalacznik.BlokDanych.Tabela.Wiersz createFakturaZalacznikBlokDanychTabelaWiersz() {
        return new Faktura.Zalacznik.BlokDanych.Tabela.Wiersz();
    }

    /**
     * Create an instance of {@link Faktura.Zalacznik.BlokDanych.Tabela.Suma }
     * 
     */
    public Faktura.Zalacznik.BlokDanych.Tabela.Suma createFakturaZalacznikBlokDanychTabelaSuma() {
        return new Faktura.Zalacznik.BlokDanych.Tabela.Suma();
    }

    /**
     * Create an instance of {@link Faktura.Zalacznik.BlokDanych.Tabela.TNaglowek.Kol.NKom }
     * 
     */
    public Faktura.Zalacznik.BlokDanych.Tabela.TNaglowek.Kol.NKom createFakturaZalacznikBlokDanychTabelaTNaglowekKolNKom() {
        return new Faktura.Zalacznik.BlokDanych.Tabela.TNaglowek.Kol.NKom();
    }

    /**
     * Create an instance of {@link Faktura.Stopka.Informacje }
     * 
     */
    public Faktura.Stopka.Informacje createFakturaStopkaInformacje() {
        return new Faktura.Stopka.Informacje();
    }

    /**
     * Create an instance of {@link Faktura.Stopka.Rejestry }
     * 
     */
    public Faktura.Stopka.Rejestry createFakturaStopkaRejestry() {
        return new Faktura.Stopka.Rejestry();
    }

    /**
     * Create an instance of {@link Faktura.Fa.OkresFa }
     * 
     */
    public Faktura.Fa.OkresFa createFakturaFaOkresFa() {
        return new Faktura.Fa.OkresFa();
    }

    /**
     * Create an instance of {@link Faktura.Fa.DaneFaKorygowanej }
     * 
     */
    public Faktura.Fa.DaneFaKorygowanej createFakturaFaDaneFaKorygowanej() {
        return new Faktura.Fa.DaneFaKorygowanej();
    }

    /**
     * Create an instance of {@link Faktura.Fa.Podmiot1K }
     * 
     */
    public Faktura.Fa.Podmiot1K createFakturaFaPodmiot1K() {
        return new Faktura.Fa.Podmiot1K();
    }

    /**
     * Create an instance of {@link Faktura.Fa.Podmiot2K }
     * 
     */
    public Faktura.Fa.Podmiot2K createFakturaFaPodmiot2K() {
        return new Faktura.Fa.Podmiot2K();
    }

    /**
     * Create an instance of {@link Faktura.Fa.ZaliczkaCzesciowa }
     * 
     */
    public Faktura.Fa.ZaliczkaCzesciowa createFakturaFaZaliczkaCzesciowa() {
        return new Faktura.Fa.ZaliczkaCzesciowa();
    }

    /**
     * Create an instance of {@link Faktura.Fa.FakturaZaliczkowa }
     * 
     */
    public Faktura.Fa.FakturaZaliczkowa createFakturaFaFakturaZaliczkowa() {
        return new Faktura.Fa.FakturaZaliczkowa();
    }

    /**
     * Create an instance of {@link Faktura.Fa.FaWiersz }
     * 
     */
    public Faktura.Fa.FaWiersz createFakturaFaFaWiersz() {
        return new Faktura.Fa.FaWiersz();
    }

    /**
     * Create an instance of {@link Faktura.Fa.Zamowienie.ZamowienieWiersz }
     * 
     */
    public Faktura.Fa.Zamowienie.ZamowienieWiersz createFakturaFaZamowienieZamowienieWiersz() {
        return new Faktura.Fa.Zamowienie.ZamowienieWiersz();
    }

    /**
     * Create an instance of {@link Faktura.Fa.WarunkiTransakcji.Umowy }
     * 
     */
    public Faktura.Fa.WarunkiTransakcji.Umowy createFakturaFaWarunkiTransakcjiUmowy() {
        return new Faktura.Fa.WarunkiTransakcji.Umowy();
    }

    /**
     * Create an instance of {@link Faktura.Fa.WarunkiTransakcji.Zamowienia }
     * 
     */
    public Faktura.Fa.WarunkiTransakcji.Zamowienia createFakturaFaWarunkiTransakcjiZamowienia() {
        return new Faktura.Fa.WarunkiTransakcji.Zamowienia();
    }

    /**
     * Create an instance of {@link Faktura.Fa.WarunkiTransakcji.Transport.Przewoznik }
     * 
     */
    public Faktura.Fa.WarunkiTransakcji.Transport.Przewoznik createFakturaFaWarunkiTransakcjiTransportPrzewoznik() {
        return new Faktura.Fa.WarunkiTransakcji.Transport.Przewoznik();
    }

    /**
     * Create an instance of {@link Faktura.Fa.Platnosc.ZaplataCzesciowa }
     * 
     */
    public Faktura.Fa.Platnosc.ZaplataCzesciowa createFakturaFaPlatnoscZaplataCzesciowa() {
        return new Faktura.Fa.Platnosc.ZaplataCzesciowa();
    }

    /**
     * Create an instance of {@link Faktura.Fa.Platnosc.Skonto }
     * 
     */
    public Faktura.Fa.Platnosc.Skonto createFakturaFaPlatnoscSkonto() {
        return new Faktura.Fa.Platnosc.Skonto();
    }

    /**
     * Create an instance of {@link Faktura.Fa.Platnosc.TerminPlatnosci.TerminOpis }
     * 
     */
    public Faktura.Fa.Platnosc.TerminPlatnosci.TerminOpis createFakturaFaPlatnoscTerminPlatnosciTerminOpis() {
        return new Faktura.Fa.Platnosc.TerminPlatnosci.TerminOpis();
    }

    /**
     * Create an instance of {@link Faktura.Fa.Rozliczenie.Obciazenia }
     * 
     */
    public Faktura.Fa.Rozliczenie.Obciazenia createFakturaFaRozliczenieObciazenia() {
        return new Faktura.Fa.Rozliczenie.Obciazenia();
    }

    /**
     * Create an instance of {@link Faktura.Fa.Rozliczenie.Odliczenia }
     * 
     */
    public Faktura.Fa.Rozliczenie.Odliczenia createFakturaFaRozliczenieOdliczenia() {
        return new Faktura.Fa.Rozliczenie.Odliczenia();
    }

    /**
     * Create an instance of {@link Faktura.Fa.Adnotacje.Zwolnienie }
     * 
     */
    public Faktura.Fa.Adnotacje.Zwolnienie createFakturaFaAdnotacjeZwolnienie() {
        return new Faktura.Fa.Adnotacje.Zwolnienie();
    }

    /**
     * Create an instance of {@link Faktura.Fa.Adnotacje.PMarzy }
     * 
     */
    public Faktura.Fa.Adnotacje.PMarzy createFakturaFaAdnotacjePMarzy() {
        return new Faktura.Fa.Adnotacje.PMarzy();
    }

    /**
     * Create an instance of {@link Faktura.Fa.Adnotacje.NoweSrodkiTransportu.NowySrodekTransportu }
     * 
     */
    public Faktura.Fa.Adnotacje.NoweSrodkiTransportu.NowySrodekTransportu createFakturaFaAdnotacjeNoweSrodkiTransportuNowySrodekTransportu() {
        return new Faktura.Fa.Adnotacje.NoweSrodkiTransportu.NowySrodekTransportu();
    }

    /**
     * Create an instance of {@link Faktura.PodmiotUpowazniony.DaneKontaktowe }
     * 
     */
    public Faktura.PodmiotUpowazniony.DaneKontaktowe createFakturaPodmiotUpowaznionyDaneKontaktowe() {
        return new Faktura.PodmiotUpowazniony.DaneKontaktowe();
    }

    /**
     * Create an instance of {@link Faktura.Podmiot3 .DaneKontaktowe }
     * 
     */
    public Faktura.Podmiot3 .DaneKontaktowe createFakturaPodmiot3DaneKontaktowe() {
        return new Faktura.Podmiot3 .DaneKontaktowe();
    }

    /**
     * Create an instance of {@link Faktura.Podmiot2 .DaneKontaktowe }
     * 
     */
    public Faktura.Podmiot2 .DaneKontaktowe createFakturaPodmiot2DaneKontaktowe() {
        return new Faktura.Podmiot2 .DaneKontaktowe();
    }

    /**
     * Create an instance of {@link Faktura.Podmiot1 .AdresKoresp }
     * 
     */
    public Faktura.Podmiot1 .AdresKoresp createFakturaPodmiot1AdresKoresp() {
        return new Faktura.Podmiot1 .AdresKoresp();
    }

    /**
     * Create an instance of {@link Faktura.Podmiot1 .DaneKontaktowe }
     * 
     */
    public Faktura.Podmiot1 .DaneKontaktowe createFakturaPodmiot1DaneKontaktowe() {
        return new Faktura.Podmiot1 .DaneKontaktowe();
    }

    /**
     * Create an instance of {@link pl.gov.crd.wzor._2025._06._25._13775.TNaglowek.KodFormularza }
     * 
     */
    public pl.gov.crd.wzor._2025._06._25._13775.TNaglowek.KodFormularza createTNaglowekKodFormularza() {
        return new pl.gov.crd.wzor._2025._06._25._13775.TNaglowek.KodFormularza();
    }

}
