//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.02.13 at 11:47:47 AM CET 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://crd.gov.pl/wzor/2025/06/25/13775/", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package pl.gov.crd.wzor._2025._06._25._13775;
