//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.02.13 at 01:05:32 PM CET 
//


package pl.gov.crd.wzor._2025._06._25._13775;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TGTU.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="TGTU"&gt;
 *   &lt;restriction base="{http://crd.gov.pl/wzor/2025/06/25/13775/}TZnakowy"&gt;
 *     &lt;enumeration value="GTU_01"/&gt;
 *     &lt;enumeration value="GTU_02"/&gt;
 *     &lt;enumeration value="GTU_03"/&gt;
 *     &lt;enumeration value="GTU_04"/&gt;
 *     &lt;enumeration value="GTU_05"/&gt;
 *     &lt;enumeration value="GTU_06"/&gt;
 *     &lt;enumeration value="GTU_07"/&gt;
 *     &lt;enumeration value="GTU_08"/&gt;
 *     &lt;enumeration value="GTU_09"/&gt;
 *     &lt;enumeration value="GTU_10"/&gt;
 *     &lt;enumeration value="GTU_11"/&gt;
 *     &lt;enumeration value="GTU_12"/&gt;
 *     &lt;enumeration value="GTU_13"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "TGTU")
@XmlEnum
public enum TGTU {


    /**
     * Dostawa towarów, o których mowa w § 10 ust. 3 pkt 1 lit. a rozporządzenia w sprawie szczegółowego zakresu danych zawartych w deklaracjach podatkowych i w ewidencji w zakresie podatku od towarów i usług
     * 
     */
    GTU_01,

    /**
     * Dostawa towarów, o których mowa w § 10 ust. 3 pkt 1 lit. b rozporządzenia w sprawie szczegółowego zakresu danych zawartych w deklaracjach podatkowych i w ewidencji w zakresie podatku od towarów i usług
     * 
     */
    GTU_02,

    /**
     * Dostawa towarów, o których mowa w § 10 ust. 3 pkt 1 lit. c rozporządzenia w sprawie szczegółowego zakresu danych zawartych w deklaracjach podatkowych i w ewidencji w zakresie podatku od towarów i usług
     * 
     */
    GTU_03,

    /**
     * Dostawa towarów, o których mowa w § 10 ust. 3 pkt 1 lit. d rozporządzenia w sprawie szczegółowego zakresu danych zawartych w deklaracjach podatkowych i w ewidencji w zakresie podatku od towarów i usług
     * 
     */
    GTU_04,

    /**
     * Dostawa towarów, o których mowa w § 10 ust. 3 pkt 1 lit. e rozporządzenia w sprawie szczegółowego zakresu danych zawartych w deklaracjach podatkowych i w ewidencji w zakresie podatku od towarów i usług
     * 
     */
    GTU_05,

    /**
     * Dostawa towarów, o których mowa w § 10 ust. 3 pkt 1 lit. f rozporządzenia w sprawie szczegółowego zakresu danych zawartych w deklaracjach podatkowych i w ewidencji w zakresie podatku od towarów i usług
     * 
     */
    GTU_06,

    /**
     * Dostawa towarów, o których mowa w § 10 ust. 3 pkt 1 lit. g rozporządzenia w sprawie szczegółowego zakresu danych zawartych w deklaracjach podatkowych i w ewidencji w zakresie podatku od towarów i usług
     * 
     */
    GTU_07,

    /**
     * Dostawa towarów, o których mowa w § 10 ust. 3 pkt 1 lit. h rozporządzenia w sprawie szczegółowego zakresu danych zawartych w deklaracjach podatkowych i w ewidencji w zakresie podatku od towarów i usług
     * 
     */
    GTU_08,

    /**
     * Dostawa towarów, o których mowa w § 10 ust. 3 pkt 1 lit. i rozporządzenia w sprawie szczegółowego zakresu danych zawartych w deklaracjach podatkowych i w ewidencji w zakresie podatku od towarów i usług
     * 
     */
    GTU_09,

    /**
     * Dostawa towarów, o których mowa w § 10 ust. 3 pkt 1 lit. j rozporządzenia w sprawie szczegółowego zakresu danych zawartych w deklaracjach podatkowych i w ewidencji w zakresie podatku od towarów i usług
     * 
     */
    GTU_10,

    /**
     * Świadczenie usług, o których mowa w § 10 ust. 3 pkt 2 lit. a rozporządzenia w sprawie szczegółowego zakresu danych zawartych w deklaracjach podatkowych i w ewidencji w zakresie podatku od towarów i usług
     * 
     */
    GTU_11,

    /**
     * Świadczenie usług, o których mowa w § 10 ust. 3 pkt 2 lit. b rozporządzenia w sprawie szczegółowego zakresu danych zawartych w deklaracjach podatkowych i w ewidencji w zakresie podatku od towarów i usług
     * 
     */
    GTU_12,

    /**
     * Świadczenie usług, o których mowa w § 10 ust. 3 pkt 2 lit. c rozporządzenia w sprawie szczegółowego zakresu danych zawartych w deklaracjach podatkowych i w ewidencji w zakresie podatku od towarów i usług
     * 
     */
    GTU_13;

    public String value() {
        return name();
    }

    public static TGTU fromValue(String v) {
        return valueOf(v);
    }

}
