//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.02.13 at 11:47:47 AM CET 
//


package pl.gov.crd.wzor._2025._06._25._13775;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TKodWaluty.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="TKodWaluty"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}normalizedString"&gt;
 *     &lt;enumeration value="AED"/&gt;
 *     &lt;enumeration value="AFN"/&gt;
 *     &lt;enumeration value="ALL"/&gt;
 *     &lt;enumeration value="AMD"/&gt;
 *     &lt;enumeration value="ANG"/&gt;
 *     &lt;enumeration value="AOA"/&gt;
 *     &lt;enumeration value="ARS"/&gt;
 *     &lt;enumeration value="AUD"/&gt;
 *     &lt;enumeration value="AWG"/&gt;
 *     &lt;enumeration value="AZN"/&gt;
 *     &lt;enumeration value="BAM"/&gt;
 *     &lt;enumeration value="BBD"/&gt;
 *     &lt;enumeration value="BDT"/&gt;
 *     &lt;enumeration value="BGN"/&gt;
 *     &lt;enumeration value="BHD"/&gt;
 *     &lt;enumeration value="BIF"/&gt;
 *     &lt;enumeration value="BMD"/&gt;
 *     &lt;enumeration value="BND"/&gt;
 *     &lt;enumeration value="BOB"/&gt;
 *     &lt;enumeration value="BOV"/&gt;
 *     &lt;enumeration value="BRL"/&gt;
 *     &lt;enumeration value="BSD"/&gt;
 *     &lt;enumeration value="BTN"/&gt;
 *     &lt;enumeration value="BWP"/&gt;
 *     &lt;enumeration value="BYN"/&gt;
 *     &lt;enumeration value="BZD"/&gt;
 *     &lt;enumeration value="CAD"/&gt;
 *     &lt;enumeration value="CDF"/&gt;
 *     &lt;enumeration value="CHE"/&gt;
 *     &lt;enumeration value="CHF"/&gt;
 *     &lt;enumeration value="CHW"/&gt;
 *     &lt;enumeration value="CLF"/&gt;
 *     &lt;enumeration value="CLP"/&gt;
 *     &lt;enumeration value="CNY"/&gt;
 *     &lt;enumeration value="COP"/&gt;
 *     &lt;enumeration value="COU"/&gt;
 *     &lt;enumeration value="CRC"/&gt;
 *     &lt;enumeration value="CUC"/&gt;
 *     &lt;enumeration value="CUP"/&gt;
 *     &lt;enumeration value="CVE"/&gt;
 *     &lt;enumeration value="CZK"/&gt;
 *     &lt;enumeration value="DJF"/&gt;
 *     &lt;enumeration value="DKK"/&gt;
 *     &lt;enumeration value="DOP"/&gt;
 *     &lt;enumeration value="DZD"/&gt;
 *     &lt;enumeration value="EGP"/&gt;
 *     &lt;enumeration value="ERN"/&gt;
 *     &lt;enumeration value="ETB"/&gt;
 *     &lt;enumeration value="EUR"/&gt;
 *     &lt;enumeration value="FJD"/&gt;
 *     &lt;enumeration value="FKP"/&gt;
 *     &lt;enumeration value="GBP"/&gt;
 *     &lt;enumeration value="GEL"/&gt;
 *     &lt;enumeration value="GGP"/&gt;
 *     &lt;enumeration value="GHS"/&gt;
 *     &lt;enumeration value="GIP"/&gt;
 *     &lt;enumeration value="GMD"/&gt;
 *     &lt;enumeration value="GNF"/&gt;
 *     &lt;enumeration value="GTQ"/&gt;
 *     &lt;enumeration value="GYD"/&gt;
 *     &lt;enumeration value="HKD"/&gt;
 *     &lt;enumeration value="HNL"/&gt;
 *     &lt;enumeration value="HRK"/&gt;
 *     &lt;enumeration value="HTG"/&gt;
 *     &lt;enumeration value="HUF"/&gt;
 *     &lt;enumeration value="IDR"/&gt;
 *     &lt;enumeration value="ILS"/&gt;
 *     &lt;enumeration value="IMP"/&gt;
 *     &lt;enumeration value="INR"/&gt;
 *     &lt;enumeration value="IQD"/&gt;
 *     &lt;enumeration value="IRR"/&gt;
 *     &lt;enumeration value="ISK"/&gt;
 *     &lt;enumeration value="JEP"/&gt;
 *     &lt;enumeration value="JMD"/&gt;
 *     &lt;enumeration value="JOD"/&gt;
 *     &lt;enumeration value="JPY"/&gt;
 *     &lt;enumeration value="KES"/&gt;
 *     &lt;enumeration value="KGS"/&gt;
 *     &lt;enumeration value="KHR"/&gt;
 *     &lt;enumeration value="KMF"/&gt;
 *     &lt;enumeration value="KPW"/&gt;
 *     &lt;enumeration value="KRW"/&gt;
 *     &lt;enumeration value="KWD"/&gt;
 *     &lt;enumeration value="KYD"/&gt;
 *     &lt;enumeration value="KZT"/&gt;
 *     &lt;enumeration value="LAK"/&gt;
 *     &lt;enumeration value="LBP"/&gt;
 *     &lt;enumeration value="LKR"/&gt;
 *     &lt;enumeration value="LRD"/&gt;
 *     &lt;enumeration value="LSL"/&gt;
 *     &lt;enumeration value="LYD"/&gt;
 *     &lt;enumeration value="MAD"/&gt;
 *     &lt;enumeration value="MDL"/&gt;
 *     &lt;enumeration value="MGA"/&gt;
 *     &lt;enumeration value="MKD"/&gt;
 *     &lt;enumeration value="MMK"/&gt;
 *     &lt;enumeration value="MNT"/&gt;
 *     &lt;enumeration value="MOP"/&gt;
 *     &lt;enumeration value="MRU"/&gt;
 *     &lt;enumeration value="MUR"/&gt;
 *     &lt;enumeration value="MVR"/&gt;
 *     &lt;enumeration value="MWK"/&gt;
 *     &lt;enumeration value="MXN"/&gt;
 *     &lt;enumeration value="MXV"/&gt;
 *     &lt;enumeration value="MYR"/&gt;
 *     &lt;enumeration value="MZN"/&gt;
 *     &lt;enumeration value="NAD"/&gt;
 *     &lt;enumeration value="NGN"/&gt;
 *     &lt;enumeration value="NIO"/&gt;
 *     &lt;enumeration value="NOK"/&gt;
 *     &lt;enumeration value="NPR"/&gt;
 *     &lt;enumeration value="NZD"/&gt;
 *     &lt;enumeration value="OMR"/&gt;
 *     &lt;enumeration value="PAB"/&gt;
 *     &lt;enumeration value="PEN"/&gt;
 *     &lt;enumeration value="PGK"/&gt;
 *     &lt;enumeration value="PHP"/&gt;
 *     &lt;enumeration value="PKR"/&gt;
 *     &lt;enumeration value="PLN"/&gt;
 *     &lt;enumeration value="PYG"/&gt;
 *     &lt;enumeration value="QAR"/&gt;
 *     &lt;enumeration value="RON"/&gt;
 *     &lt;enumeration value="RSD"/&gt;
 *     &lt;enumeration value="RUB"/&gt;
 *     &lt;enumeration value="RWF"/&gt;
 *     &lt;enumeration value="SAR"/&gt;
 *     &lt;enumeration value="SBD"/&gt;
 *     &lt;enumeration value="SCR"/&gt;
 *     &lt;enumeration value="SDG"/&gt;
 *     &lt;enumeration value="SEK"/&gt;
 *     &lt;enumeration value="SGD"/&gt;
 *     &lt;enumeration value="SHP"/&gt;
 *     &lt;enumeration value="SLL"/&gt;
 *     &lt;enumeration value="SOS"/&gt;
 *     &lt;enumeration value="SRD"/&gt;
 *     &lt;enumeration value="SSP"/&gt;
 *     &lt;enumeration value="STN"/&gt;
 *     &lt;enumeration value="SVC"/&gt;
 *     &lt;enumeration value="SYP"/&gt;
 *     &lt;enumeration value="SZL"/&gt;
 *     &lt;enumeration value="THB"/&gt;
 *     &lt;enumeration value="TJS"/&gt;
 *     &lt;enumeration value="TMT"/&gt;
 *     &lt;enumeration value="TND"/&gt;
 *     &lt;enumeration value="TOP"/&gt;
 *     &lt;enumeration value="TRY"/&gt;
 *     &lt;enumeration value="TTD"/&gt;
 *     &lt;enumeration value="TWD"/&gt;
 *     &lt;enumeration value="TZS"/&gt;
 *     &lt;enumeration value="UAH"/&gt;
 *     &lt;enumeration value="UGX"/&gt;
 *     &lt;enumeration value="USD"/&gt;
 *     &lt;enumeration value="USN"/&gt;
 *     &lt;enumeration value="UYI"/&gt;
 *     &lt;enumeration value="UYU"/&gt;
 *     &lt;enumeration value="UYW"/&gt;
 *     &lt;enumeration value="UZS"/&gt;
 *     &lt;enumeration value="VES"/&gt;
 *     &lt;enumeration value="VND"/&gt;
 *     &lt;enumeration value="VUV"/&gt;
 *     &lt;enumeration value="WST"/&gt;
 *     &lt;enumeration value="XAF"/&gt;
 *     &lt;enumeration value="XAG"/&gt;
 *     &lt;enumeration value="XAU"/&gt;
 *     &lt;enumeration value="XBA"/&gt;
 *     &lt;enumeration value="XBB"/&gt;
 *     &lt;enumeration value="XBC"/&gt;
 *     &lt;enumeration value="XBD"/&gt;
 *     &lt;enumeration value="XCD"/&gt;
 *     &lt;enumeration value="XCG"/&gt;
 *     &lt;enumeration value="XDR"/&gt;
 *     &lt;enumeration value="XOF"/&gt;
 *     &lt;enumeration value="XPD"/&gt;
 *     &lt;enumeration value="XPF"/&gt;
 *     &lt;enumeration value="XPT"/&gt;
 *     &lt;enumeration value="XSU"/&gt;
 *     &lt;enumeration value="XUA"/&gt;
 *     &lt;enumeration value="XXX"/&gt;
 *     &lt;enumeration value="YER"/&gt;
 *     &lt;enumeration value="ZAR"/&gt;
 *     &lt;enumeration value="ZMW"/&gt;
 *     &lt;enumeration value="ZWL"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "TKodWaluty")
@XmlEnum
public enum TKodWaluty {


    /**
     * DIRHAM ZEA
     * 
     */
    AED,

    /**
     * AFGANI
     * 
     */
    AFN,

    /**
     * LEK
     * 
     */
    ALL,

    /**
     * DRAM
     * 
     */
    AMD,

    /**
     * GULDEN ANTYLI HOLENDERSKICH
     * 
     */
    ANG,

    /**
     * KWANZA
     * 
     */
    AOA,

    /**
     * PESO ARGENTYŃSKIE
     * 
     */
    ARS,

    /**
     * DOLAR AUSTRALIJSKI
     * 
     */
    AUD,

    /**
     * GULDEN ARUBAŃSKI
     * 
     */
    AWG,

    /**
     * MANAT AZERBEJDŻAŃSKI
     * 
     */
    AZN,

    /**
     * MARKA ZAMIENNA
     * 
     */
    BAM,

    /**
     * DOLAR BARBADOSKI
     * 
     */
    BBD,

    /**
     * TAKA
     * 
     */
    BDT,

    /**
     * LEW
     * 
     */
    BGN,

    /**
     * DINAR BAHRAJSKI
     * 
     */
    BHD,

    /**
     * FRANK BURUNDYJSKI
     * 
     */
    BIF,

    /**
     * DOLAR BERMUDZKI
     * 
     */
    BMD,

    /**
     * DOLAR BRUNEJSKI
     * 
     */
    BND,

    /**
     * BOLIWIANO
     * 
     */
    BOB,

    /**
     * BOLIWIANO MVDOL
     * 
     */
    BOV,

    /**
     * REAL
     * 
     */
    BRL,

    /**
     * DOLAR BAHAMSKI
     * 
     */
    BSD,

    /**
     * NGULTRUM
     * 
     */
    BTN,

    /**
     * PULA
     * 
     */
    BWP,

    /**
     * RUBEL BIAŁORUSKI
     * 
     */
    BYN,

    /**
     * DOLAR BELIZEŃSKI
     * 
     */
    BZD,

    /**
     * DOLAR KANADYJSKI
     * 
     */
    CAD,

    /**
     * FRANK KONGIJSKI
     * 
     */
    CDF,

    /**
     * FRANK SZWAJCARSKI VIR EURO
     * 
     */
    CHE,

    /**
     * FRANK SZWAJCARSKI
     * 
     */
    CHF,

    /**
     * FRANK SZWAJCARSKI VIR FRANK
     * 
     */
    CHW,

    /**
     * JEDNOSTKA ROZLICZENIOWA CHILIJSKA
     * 
     */
    CLF,

    /**
     * PESO CHILIJSKIE
     * 
     */
    CLP,

    /**
     * YUAN RENMINBI
     * 
     */
    CNY,

    /**
     * PESO KOLUMBIJSKIE
     * 
     */
    COP,

    /**
     * UNIDAD DE VALOR REAL KOLUMBILSKIE
     * 
     */
    COU,

    /**
     * COLON KOSTARYKAŃSKI
     * 
     */
    CRC,

    /**
     * PESO WYMIENIALNE
     * 
     */
    CUC,

    /**
     * PESO KUBAŃSKIE
     * 
     */
    CUP,

    /**
     * ESCUDO REPUBLIKI ZIELONEGO PRZYLĄDKA
     * 
     */
    CVE,

    /**
     * KORONA CZESKA
     * 
     */
    CZK,

    /**
     * FRANK DŻIBUTI
     * 
     */
    DJF,

    /**
     * KORONA DUŃSKA
     * 
     */
    DKK,

    /**
     * PESO DOMINIKAŃSKIE
     * 
     */
    DOP,

    /**
     * DINAR ALGIERSKI
     * 
     */
    DZD,

    /**
     * FUNT EGIPSKI
     * 
     */
    EGP,

    /**
     * NAKFA
     * 
     */
    ERN,

    /**
     * BIRR
     * 
     */
    ETB,

    /**
     * EURO
     * 
     */
    EUR,

    /**
     * DOLAR FIDŻI
     * 
     */
    FJD,

    /**
     * FUNT FALKLANDZKI
     * 
     */
    FKP,

    /**
     * FUNT SZTERLING
     * 
     */
    GBP,

    /**
     * LARI
     * 
     */
    GEL,

    /**
     * FUNT GUERNSEY
     * 
     */
    GGP,

    /**
     * GHANA CEDI
     * 
     */
    GHS,

    /**
     * FUNT GIBRALTARSKI
     * 
     */
    GIP,

    /**
     * DALASI
     * 
     */
    GMD,

    /**
     * FRANK GWINEJSKI
     * 
     */
    GNF,

    /**
     * QUETZAL
     * 
     */
    GTQ,

    /**
     * DOLAR GUJAŃSKI
     * 
     */
    GYD,

    /**
     * DOLAR HONGKONGU
     * 
     */
    HKD,

    /**
     * LEMPIRA
     * 
     */
    HNL,

    /**
     * KUNA
     * 
     */
    HRK,

    /**
     * GOURDE
     * 
     */
    HTG,

    /**
     * FORINT
     * 
     */
    HUF,

    /**
     * RUPIA INDONEZYJSKA
     * 
     */
    IDR,

    /**
     * SZEKEL
     * 
     */
    ILS,

    /**
     * FUNT MANX
     * 
     */
    IMP,

    /**
     * RUPIA INDYJSKA
     * 
     */
    INR,

    /**
     * DINAR IRACKI
     * 
     */
    IQD,

    /**
     * RIAL IRAŃSKI
     * 
     */
    IRR,

    /**
     * KORONA ISLANDZKA
     * 
     */
    ISK,

    /**
     * FUNT JERSEY
     * 
     */
    JEP,

    /**
     * DOLAR JAMAJSKI
     * 
     */
    JMD,

    /**
     * DINAR JORDAŃSKI
     * 
     */
    JOD,

    /**
     * JEN
     * 
     */
    JPY,

    /**
     * SZYLING KENIJSKI
     * 
     */
    KES,

    /**
     * SOM
     * 
     */
    KGS,

    /**
     * RIEL
     * 
     */
    KHR,

    /**
     * FRANK KOMORÓW
     * 
     */
    KMF,

    /**
     * WON PÓŁNOCNO­KOREAŃSKI
     * 
     */
    KPW,

    /**
     * WON POŁUDNIOWO­KOREAŃSKI
     * 
     */
    KRW,

    /**
     * DINAR KUWEJCKI
     * 
     */
    KWD,

    /**
     * DOLAR KAJMAŃSKI
     * 
     */
    KYD,

    /**
     * TENGE
     * 
     */
    KZT,

    /**
     * KIP
     * 
     */
    LAK,

    /**
     * FUNT LIBAŃSKI
     * 
     */
    LBP,

    /**
     * RUPIA LANKIJSKA
     * 
     */
    LKR,

    /**
     * DOLAR LIBERYJSKI
     * 
     */
    LRD,

    /**
     * LOTI
     * 
     */
    LSL,

    /**
     * DINAR LIBIJSKI
     * 
     */
    LYD,

    /**
     * DIRHAM MAROKAŃSKI
     * 
     */
    MAD,

    /**
     * LEJ MOŁDAWII
     * 
     */
    MDL,

    /**
     * ARIARY
     * 
     */
    MGA,

    /**
     * DENAR
     * 
     */
    MKD,

    /**
     * KYAT
     * 
     */
    MMK,

    /**
     * TUGRIK
     * 
     */
    MNT,

    /**
     * PATACA
     * 
     */
    MOP,

    /**
     * OUGUIYA
     * 
     */
    MRU,

    /**
     * RUPIA MAURITIUSU
     * 
     */
    MUR,

    /**
     * RUPIA MALEDIWSKA
     * 
     */
    MVR,

    /**
     * KWACHA MALAWIJSKA
     * 
     */
    MWK,

    /**
     * PESO MEKSYKAŃSKIE
     * 
     */
    MXN,

    /**
     * UNIDAD DE INVERSION (UDI) MEKSYKAŃSKIE
     * 
     */
    MXV,

    /**
     * RINGGIT
     * 
     */
    MYR,

    /**
     * METICAL
     * 
     */
    MZN,

    /**
     * DOLAR NAMIBIJSKI
     * 
     */
    NAD,

    /**
     * NAIRA
     * 
     */
    NGN,

    /**
     * CORDOBA ORO
     * 
     */
    NIO,

    /**
     * KORONA NORWESKA
     * 
     */
    NOK,

    /**
     * RUPIA NEPALSKA
     * 
     */
    NPR,

    /**
     * DOLAR NOWOZELANDZKI
     * 
     */
    NZD,

    /**
     * RIAL OMAŃSKI
     * 
     */
    OMR,

    /**
     * BALBOA
     * 
     */
    PAB,

    /**
     * SOL
     * 
     */
    PEN,

    /**
     * KINA
     * 
     */
    PGK,

    /**
     * PESO FILIPIŃSKIE
     * 
     */
    PHP,

    /**
     * RUPIA PAKISTAŃSKA
     * 
     */
    PKR,

    /**
     * ZŁOTY
     * 
     */
    PLN,

    /**
     * GUARANI
     * 
     */
    PYG,

    /**
     * RIAL KATARSKI
     * 
     */
    QAR,

    /**
     * LEJ RUMUŃSKI
     * 
     */
    RON,

    /**
     * DINAR SERBSKI
     * 
     */
    RSD,

    /**
     * RUBEL ROSYJSKI
     * 
     */
    RUB,

    /**
     * FRANK RWANDYJSKI
     * 
     */
    RWF,

    /**
     * RIAL SAUDYJSKI
     * 
     */
    SAR,

    /**
     * DOLAR WYSP SALOMONA
     * 
     */
    SBD,

    /**
     * RUPIA SESZELSKA
     * 
     */
    SCR,

    /**
     * FUNT SUDAŃSKI
     * 
     */
    SDG,

    /**
     * KORONA SZWEDZKA
     * 
     */
    SEK,

    /**
     * DOLAR SINGAPURSKI
     * 
     */
    SGD,

    /**
     * FUNT ŚWIĘTEJ HELENY (ŚWIĘTA HELENA I WYSPA WNIEBOWSTĄPIENIA)
     * 
     */
    SHP,

    /**
     * LEONE
     * 
     */
    SLL,

    /**
     * SZYLING SOMALIJSKI
     * 
     */
    SOS,

    /**
     * DOLAR SURINAMSKI
     * 
     */
    SRD,

    /**
     * FUNT POŁUDNIOWOSUDAŃSKI
     * 
     */
    SSP,

    /**
     * DOBRA
     * 
     */
    STN,

    /**
     * COLON SALWADORSKI (SV1)
     * 
     */
    SVC,

    /**
     * FUNT SYRYJSKI
     * 
     */
    SYP,

    /**
     * LILANGENI
     * 
     */
    SZL,

    /**
     * BAT
     * 
     */
    THB,

    /**
     * SOMONI
     * 
     */
    TJS,

    /**
     * MANAT TURKMEŃSKI
     * 
     */
    TMT,

    /**
     * DINAR TUNEZYJSKI
     * 
     */
    TND,

    /**
     * PAANGA
     * 
     */
    TOP,

    /**
     * LIRA TURECKA
     * 
     */
    TRY,

    /**
     * DOLAR TRYNIDADU I TOBAGO
     * 
     */
    TTD,

    /**
     * NOWY DOLAR TAJWAŃSKI
     * 
     */
    TWD,

    /**
     * SZYLING TANZAŃSKI
     * 
     */
    TZS,

    /**
     * HRYWNA
     * 
     */
    UAH,

    /**
     * SZYLING UGANDYJSKI
     * 
     */
    UGX,

    /**
     * DOLAR AMERYKAŃSKI
     * 
     */
    USD,

    /**
     * DOLAR AMERYKAŃSKI (NEXT DAY)
     * 
     */
    USN,

    /**
     * PESO EN UNIDADES INDEXADAS URUGWAJSKIE
     * 
     */
    UYI,

    /**
     * PESO URUGWAJSKIE
     * 
     */
    UYU,

    /**
     * PESO EN UNIDADES INDEXADAS URUGWAJSKIE
     * 
     */
    UYW,

    /**
     * SUM
     * 
     */
    UZS,

    /**
     * BOLIWAR SOBERANO 
     * 
     */
    VES,

    /**
     * DONG
     * 
     */
    VND,

    /**
     * VATU
     * 
     */
    VUV,

    /**
     * TALA
     * 
     */
    WST,

    /**
     * FRANK CFA (BEAC)
     * 
     */
    XAF,

    /**
     * SREBRO
     * 
     */
    XAG,

    /**
     * ZŁOTO
     * 
     */
    XAU,

    /**
     * BOND MARKETS UNIT EUROPEAN COMPOSITE UNIT (EURCO)
     * 
     */
    XBA,

    /**
     * BOND MARKETS UNIT EUROPEAN MONETARY UNIT (E.M.U.-6)
     * 
     */
    XBB,

    /**
     * BOND MARKETS UNIT EUROPEAN UNIT OF ACCOUNT 9 (E.U.A.-9)
     * 
     */
    XBC,

    /**
     * BOND MARKETS UNIT EUROPEAN UNIT OF ACCOUNT 17 (E.U.A.-17)
     * 
     */
    XBD,

    /**
     * DOLAR WSCHODNIO­KARAIBSKI
     * 
     */
    XCD,

    /**
     * GULDEN KARAIBSKI
     * 
     */
    XCG,

    /**
     * SDR MIĘDZYNARODOWY FUNDUSZ WALUTOWY
     * 
     */
    XDR,

    /**
     * FRANK CFA (BCEAO)
     * 
     */
    XOF,

    /**
     * PALLAD
     * 
     */
    XPD,

    /**
     * FRANK CFP
     * 
     */
    XPF,

    /**
     * PLATYNA
     * 
     */
    XPT,

    /**
     * SUCRE SISTEMA UNITARIO DE COMPENSACION REGIONAL DE PAGOS SUCRE
     * 
     */
    XSU,

    /**
     * ADB UNIT OF ACCOUNT MEMBER COUNTRIES OF THE AFRICAN DEVELOPMENT BANK GROUP
     * 
     */
    XUA,

    /**
     * BRAK WALUTY
     * 
     */
    XXX,

    /**
     * RIAL JEMEŃSKI
     * 
     */
    YER,

    /**
     * RAND
     * 
     */
    ZAR,

    /**
     * KWACHA ZAMBIJSKA
     * 
     */
    ZMW,

    /**
     * DOLAR ZIMBABWE
     * 
     */
    ZWL;

    public String value() {
        return name();
    }

    public static TKodWaluty fromValue(String v) {
        return valueOf(v);
    }

}
