//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.02.13 at 01:05:32 PM CET 
//


package pl.gov.crd.wzor._2025._06._25._13775;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TKodyKrajowUE.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="TKodyKrajowUE"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}normalizedString"&gt;
 *     &lt;enumeration value="AT"/&gt;
 *     &lt;enumeration value="BE"/&gt;
 *     &lt;enumeration value="BG"/&gt;
 *     &lt;enumeration value="CY"/&gt;
 *     &lt;enumeration value="CZ"/&gt;
 *     &lt;enumeration value="DK"/&gt;
 *     &lt;enumeration value="EE"/&gt;
 *     &lt;enumeration value="FI"/&gt;
 *     &lt;enumeration value="FR"/&gt;
 *     &lt;enumeration value="DE"/&gt;
 *     &lt;enumeration value="EL"/&gt;
 *     &lt;enumeration value="HR"/&gt;
 *     &lt;enumeration value="HU"/&gt;
 *     &lt;enumeration value="IE"/&gt;
 *     &lt;enumeration value="IT"/&gt;
 *     &lt;enumeration value="LV"/&gt;
 *     &lt;enumeration value="LT"/&gt;
 *     &lt;enumeration value="LU"/&gt;
 *     &lt;enumeration value="MT"/&gt;
 *     &lt;enumeration value="NL"/&gt;
 *     &lt;enumeration value="PL"/&gt;
 *     &lt;enumeration value="PT"/&gt;
 *     &lt;enumeration value="RO"/&gt;
 *     &lt;enumeration value="SK"/&gt;
 *     &lt;enumeration value="SI"/&gt;
 *     &lt;enumeration value="ES"/&gt;
 *     &lt;enumeration value="SE"/&gt;
 *     &lt;enumeration value="XI"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "TKodyKrajowUE")
@XmlEnum
public enum TKodyKrajowUE {


    /**
     * AUSTRIA
     * 
     */
    AT,

    /**
     * BELGIA
     * 
     */
    BE,

    /**
     * BUŁGARIA
     * 
     */
    BG,

    /**
     * CYPR
     * 
     */
    CY,

    /**
     * CZECHY
     * 
     */
    CZ,

    /**
     * DANIA
     * 
     */
    DK,

    /**
     * ESTONIA
     * 
     */
    EE,

    /**
     * FINLANDIA
     * 
     */
    FI,

    /**
     * FRANCJA
     * 
     */
    FR,

    /**
     * NIEMCY
     * 
     */
    DE,

    /**
     * GRECJA
     * 
     */
    EL,

    /**
     * CHORWACJA
     * 
     */
    HR,

    /**
     * WĘGRY
     * 
     */
    HU,

    /**
     * IRLANDIA
     * 
     */
    IE,

    /**
     * WŁOCHY
     * 
     */
    IT,

    /**
     * ŁOTWA
     * 
     */
    LV,

    /**
     * LITWA
     * 
     */
    LT,

    /**
     * LUKSEMBURG
     * 
     */
    LU,

    /**
     * MALTA
     * 
     */
    MT,

    /**
     * HOLANDIA
     * 
     */
    NL,

    /**
     * POLSKA
     * 
     */
    PL,

    /**
     * PORTUGALIA
     * 
     */
    PT,

    /**
     * RUMUNIA
     * 
     */
    RO,

    /**
     * SŁOWACJA
     * 
     */
    SK,

    /**
     * SŁOWENIA
     * 
     */
    SI,

    /**
     * HISZPANIA
     * 
     */
    ES,

    /**
     * SZWECJA
     * 
     */
    SE,

    /**
     * IRLANDIA PÓŁNOCNA
     * 
     */
    XI;

    public String value() {
        return name();
    }

    public static TKodyKrajowUE fromValue(String v) {
        return valueOf(v);
    }

}
