//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.02.13 at 01:05:32 PM CET 
//


package pl.gov.crd.wzor._2025._06._25._13775;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TOznaczenieProcedury.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="TOznaczenieProcedury"&gt;
 *   &lt;restriction base="{http://crd.gov.pl/wzor/2025/06/25/13775/}TZnakowy"&gt;
 *     &lt;enumeration value="WSTO_EE"/&gt;
 *     &lt;enumeration value="IED"/&gt;
 *     &lt;enumeration value="TT_D"/&gt;
 *     &lt;enumeration value="I_42"/&gt;
 *     &lt;enumeration value="I_63"/&gt;
 *     &lt;enumeration value="B_SPV"/&gt;
 *     &lt;enumeration value="B_SPV_DOSTAWA"/&gt;
 *     &lt;enumeration value="B_MPV_PROWIZJA"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "TOznaczenieProcedury")
@XmlEnum
public enum TOznaczenieProcedury {


    /**
     * Oznaczenie dotyczące procedury, o której mowa w § 10 ust. 4 pkt 2a rozporządzenia w sprawie szczegółowego zakresu danych zawartych w deklaracjach podatkowych i w ewidencji w zakresie podatku od towarów i usług
     * 
     */
    WSTO_EE,

    /**
     * Oznaczenie dotyczące procedury, o której mowa w § 10 ust. 4 pkt 2b rozporządzenia w sprawie szczegółowego zakresu danych zawartych w deklaracjach podatkowych i w ewidencji w zakresie podatku od towarów i usług
     * 
     */
    IED,

    /**
     * Oznaczenie dotyczące procedury, o której mowa w § 10 ust. 4 pkt 5 rozporządzenia w sprawie szczegółowego zakresu danych zawartych w deklaracjach podatkowych i w ewidencji w zakresie podatku od towarów i usług
     * 
     */
    TT_D,

    /**
     * Oznaczenie dotyczące procedury, o której mowa w § 10 ust. 4 pkt 8 rozporządzenia w sprawie szczegółowego zakresu danych zawartych w deklaracjach podatkowych i w ewidencji w zakresie podatku od towarów i usług
     * 
     */
    I_42,

    /**
     * Oznaczenie dotyczące procedury, o której mowa w § 10 ust. 4 pkt 9 rozporządzenia w sprawie szczegółowego zakresu danych zawartych w deklaracjach podatkowych i w ewidencji w zakresie podatku od towarów i usług
     * 
     */
    I_63,

    /**
     * Oznaczenie dotyczące procedury, o której mowa w § 10 ust. 4 pkt 10 rozporządzenia w sprawie szczegółowego zakresu danych zawartych w deklaracjach podatkowych i w ewidencji w zakresie podatku od towarów i usług
     * 
     */
    B_SPV,

    /**
     * Oznaczenie dotyczące procedury, o której mowa w § 10 ust. 4 pkt 11 rozporządzenia w sprawie szczegółowego zakresu danych zawartych w deklaracjach podatkowych i w ewidencji w zakresie podatku od towarów i usług
     * 
     */
    B_SPV_DOSTAWA,

    /**
     * Oznaczenie dotyczące procedury, o której mowa w § 10 ust. 4 pkt 12 rozporządzenia w sprawie szczegółowego zakresu danych zawartych w deklaracjach podatkowych i w ewidencji w zakresie podatku od towarów i usług
     * 
     */
    B_MPV_PROWIZJA;

    public String value() {
        return name();
    }

    public static TOznaczenieProcedury fromValue(String v) {
        return valueOf(v);
    }

}
