//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.02.13 at 01:05:32 PM CET 
//


package pl.gov.crd.wzor._2025._06._25._13775;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import pl.gov.crd.xml.schematy.dziedzinowe.mf._2022._01._05.ed.definicjetypy.TKodKraju;


/**
 * Zestaw danych identyfikacyjnych oraz danych adresowych nabywcy
 * 
 * <p>Java class for TPodmiot2 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TPodmiot2"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;choice&gt;
 *           &lt;element name="NIP" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/01/05/eD/DefinicjeTypy/}TNrNIP"/&gt;
 *           &lt;sequence&gt;
 *             &lt;element name="KodUE" type="{http://crd.gov.pl/wzor/2025/06/25/13775/}TKodyKrajowUE"/&gt;
 *             &lt;element name="NrVatUE" type="{http://crd.gov.pl/wzor/2025/06/25/13775/}TNrVatUE"/&gt;
 *           &lt;/sequence&gt;
 *           &lt;sequence&gt;
 *             &lt;element name="KodKraju" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/01/05/eD/DefinicjeTypy/}TKodKraju" minOccurs="0"/&gt;
 *             &lt;element name="NrID"&gt;
 *               &lt;simpleType&gt;
 *                 &lt;restriction base="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/01/05/eD/DefinicjeTypy/}TNrIdentyfikacjiPodatkowej"&gt;
 *                 &lt;/restriction&gt;
 *               &lt;/simpleType&gt;
 *             &lt;/element&gt;
 *           &lt;/sequence&gt;
 *           &lt;element name="BrakID" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/01/05/eD/DefinicjeTypy/}TWybor1"/&gt;
 *         &lt;/choice&gt;
 *         &lt;sequence minOccurs="0"&gt;
 *           &lt;element name="Nazwa" type="{http://crd.gov.pl/wzor/2025/06/25/13775/}TZnakowy512"/&gt;
 *         &lt;/sequence&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TPodmiot2", propOrder = {
    "nip",
    "kodUE",
    "nrVatUE",
    "kodKraju",
    "nrID",
    "brakID",
    "nazwa"
})
public class TPodmiot2 {

    @XmlElement(name = "NIP")
    protected String nip;
    @XmlElement(name = "KodUE")
    @XmlSchemaType(name = "normalizedString")
    protected TKodyKrajowUE kodUE;
    @XmlElement(name = "NrVatUE")
    protected String nrVatUE;
    @XmlElement(name = "KodKraju")
    @XmlSchemaType(name = "normalizedString")
    protected TKodKraju kodKraju;
    @XmlElement(name = "NrID")
    protected String nrID;
    @XmlElement(name = "BrakID")
    protected Byte brakID;
    @XmlElement(name = "Nazwa")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String nazwa;

    /**
     * Gets the value of the nip property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNIP() {
        return nip;
    }

    /**
     * Sets the value of the nip property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNIP(String value) {
        this.nip = value;
    }

    /**
     * Gets the value of the kodUE property.
     * 
     * @return
     *     possible object is
     *     {@link TKodyKrajowUE }
     *     
     */
    public TKodyKrajowUE getKodUE() {
        return kodUE;
    }

    /**
     * Sets the value of the kodUE property.
     * 
     * @param value
     *     allowed object is
     *     {@link TKodyKrajowUE }
     *     
     */
    public void setKodUE(TKodyKrajowUE value) {
        this.kodUE = value;
    }

    /**
     * Gets the value of the nrVatUE property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNrVatUE() {
        return nrVatUE;
    }

    /**
     * Sets the value of the nrVatUE property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNrVatUE(String value) {
        this.nrVatUE = value;
    }

    /**
     * Gets the value of the kodKraju property.
     * 
     * @return
     *     possible object is
     *     {@link TKodKraju }
     *     
     */
    public TKodKraju getKodKraju() {
        return kodKraju;
    }

    /**
     * Sets the value of the kodKraju property.
     * 
     * @param value
     *     allowed object is
     *     {@link TKodKraju }
     *     
     */
    public void setKodKraju(TKodKraju value) {
        this.kodKraju = value;
    }

    /**
     * Gets the value of the nrID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNrID() {
        return nrID;
    }

    /**
     * Sets the value of the nrID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNrID(String value) {
        this.nrID = value;
    }

    /**
     * Gets the value of the brakID property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public Byte getBrakID() {
        return brakID;
    }

    /**
     * Sets the value of the brakID property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setBrakID(Byte value) {
        this.brakID = value;
    }

    /**
     * Gets the value of the nazwa property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNazwa() {
        return nazwa;
    }

    /**
     * Sets the value of the nazwa property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNazwa(String value) {
        this.nazwa = value;
    }

}
