//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.02.13 at 01:05:32 PM CET 
//


package pl.gov.crd.wzor._2025._06._25._13775;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TRodzajFaktury.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="TRodzajFaktury"&gt;
 *   &lt;restriction base="{http://crd.gov.pl/wzor/2025/06/25/13775/}TZnakowy"&gt;
 *     &lt;enumeration value="VAT"/&gt;
 *     &lt;enumeration value="KOR"/&gt;
 *     &lt;enumeration value="ZAL"/&gt;
 *     &lt;enumeration value="ROZ"/&gt;
 *     &lt;enumeration value="UPR"/&gt;
 *     &lt;enumeration value="KOR_ZAL"/&gt;
 *     &lt;enumeration value="KOR_ROZ"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "TRodzajFaktury")
@XmlEnum
public enum TRodzajFaktury {


    /**
     * Faktura podstawowa
     * 
     */
    VAT,

    /**
     * Faktura korygująca
     * 
     */
    KOR,

    /**
     * Faktura dokumentująca otrzymanie zapłaty lub jej części przed dokonaniem czynności oraz faktura wystawiona w związku z art. 106f ust. 4 ustawy (faktura zaliczkowa)
     * 
     */
    ZAL,

    /**
     * Faktura wystawiona w związku z art. 106f ust. 3 ustawy
     * 
     */
    ROZ,

    /**
     * Faktura, o której mowa w art. 106e ust. 5 pkt 3 ustawy
     * 
     */
    UPR,

    /**
     * Faktura korygująca fakturę dokumentującą otrzymanie zapłaty lub jej części przed dokonaniem czynności oraz fakturę wystawioną w związku z art. 106f ust. 4 ustawy (faktura korygująca fakturę zaliczkową)
     * 
     */
    KOR_ZAL,

    /**
     * Faktura korygująca fakturę wystawioną w związku z art. 106f ust. 3 ustawy
     * 
     */
    KOR_ROZ;

    public String value() {
        return name();
    }

    public static TRodzajFaktury fromValue(String v) {
        return valueOf(v);
    }

}
